### ISSUE TITLE
[BUG] Apps crashes with Zygisk (Magisk 24.1)

### ISSUE THREAD

**Issue by c3k** [Androidacy/FontManager-Module#8]
**Describe the bug**
App that tries to detect root crashes with font manager module active

**To Reproduce**
1. Installa Magisk 24.1
2. Install FontManager module (font 188 ProductFontVTwo selected, in my case)
3. Install momo https://www.dropbox.com/s/u622kw2poaaj8bw/momo-v4.0.1-280430-o_1fk1livbfar01i5m6mmqogvdjr-uid-238725.apk?dl=1
4. Activate Zygisk in Magisk
5. Put Momo in Zygisk DenyList
6. Reboot
7. Open Momo

**Expected behavior**
App continue to run

**Device info(please complete the following information):**
 - Device: Samsung S21 SM-G991B
 - OS: Android 12 G991BXXU4BVA9 (stock)
 -  Module Version 5.5.6

**Additional context**
App crashes, same with PosteID (https://play.google.com/store/apps/details?id=posteitaliane.posteapp.appposteid&hl=it&gl=US). Both works with FontManager module disabled or with Magisk 23 or with other font change module
Logcat: [momo 4.0.1 crash when in zygist deny list.txt](https://github.com/Androidacy/FontManager-Module/files/8151898/momo.4.0.1.crash.when.in.zygist.deny.list.txt)

**Comment by HuskyDG** [comment]
**SORRY, THAT'S NOT FONT MANAGER MODULE PROBLEM AND YOUR ISSUE IS INVAILID**

**Comment by c3k** [comment]
Crash stack starts with populateSkFont(), so I disabled your module and everything works again.
Same happen with another app.
Just my two cents

**Comment by HuskyDG** [comment]
That's Android 12 new behavior, font is loaded after UI is dawn so font module can't co-exist with Denylist/Shamiko
Denylist/Shamiko unmounts all modules as well. It has to do for hiding purpose.
Try flash this module: http://github.com/huskydg/magisk_overlayfs
And use file manager, go to `/data/adb/modules/magisk_overlayfs` and create a file with the name `enable`

**Comment by HuskyDG** [comment]
Try overlayfs
